name: Deploy Ninescent First

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Make application-prod.yml
      run: |
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.YML }}" > ./application.yml
      shell: bash
      
    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@v2.4.2 
    #   with:
    #     arguments: build
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build -x test

    - name: Check jar file
      run: ls ./build/libs
      
    - name: Naming jar file
      run: mv ./build/libs/mall-0.0.1-SNAPSHOT.jar ./build/libs/app.jar

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/app.jar

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Upload jar to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "./build/libs/app.jar"
        target: "/home/${{ secrets.EC2_USERNAME }}/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          pkill -f 'java -jar' || echo 'No process to kill'
          nohup java -jar /home/${{ secrets.EC2_USERNAME }}/app.jar > /dev/null 2>&1 &

