name: Deploy Ninescent First

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # 1. vm에서 리파지토리를 내려받음
    - uses: actions/checkout@v3
    # 2. vm에 jdk를 세팅함
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    # 3. application.yml 파일 생성
    - name: Make application-prod.yml
      run: |
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.YML }}" > ./application.yml
      shell: bash
      
    # 4. gradle 실행
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build -x test

    # 5. jar파일 확인 및 파일명 수정
    - name: Check jar file
      run: ls ./build/libs
      
    - name: Naming jar file
      run: mv ./build/libs/NineScents-Backend-0.0.1-SNAPSHOT.jar ./build/libs/app.jar

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/app.jar

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app  
        
    - name: Test SSH connection (telnet)
      run: |
       telnet ${{ secrets.EC2_HOST }} 22 || echo "Port 22 is not open!"
    # 1. jar 파일 EC2로 업로드
    - name: Upload jar to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "app.jar"
        target: "/home/ec2-user/"

    # 2. EC2 접속 후 배포 스크립트 실행
    # 포트 기반 프로세스 종료 pkill -f 'app.jar'이 오류여서 
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          echo "Stop existing app"
          JAVA_PID=$(sudo lsof -t -i:8080)
          if [ ! -z "$JAVA_PID" ]; then
            sudo kill $JAVA_PID
            echo "Application running on port 8080 stopped"
            sleep 5 # 프로세스가 완전히 종료될 때까지 대기
          fi
          
          echo "Run new app"
          sudo nohup java -jar /home/ec2-user/app.jar > /dev/null 2>&1 &
          echo "Done!" 
